// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZo91MeAAzwxgY4rpWLfIH0iz7xfpPpwo',
    appId: '1:359577654813:android:cc98bb2feb51b9fc7118f4',
    messagingSenderId: '359577654813',
    projectId: 'mission-board-b8dbc',
    storageBucket: 'mission-board-b8dbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBseaVZigrpHT64u5kuZ0YxDHsYJtQlVoA',
    appId: '1:359577654813:ios:1bb86bd7db9307127118f4',
    messagingSenderId: '359577654813',
    projectId: 'mission-board-b8dbc',
    storageBucket: 'mission-board-b8dbc.firebasestorage.app',
    iosClientId:
        '359577654813-odp48tjhqgdn7atlcvqm60pv9dtd4fpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.missionBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBseaVZigrpHT64u5kuZ0YxDHsYJtQlVoA',
    appId: '1:359577654813:ios:1bb86bd7db9307127118f4',
    messagingSenderId: '359577654813',
    projectId: 'mission-board-b8dbc',
    storageBucket: 'mission-board-b8dbc.firebasestorage.app',
    iosClientId:
        '359577654813-odp48tjhqgdn7atlcvqm60pv9dtd4fpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.missionBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqBqOi5HI2GqcWAXJSjqDzgNRhNW9zXlU',
    appId: '1:359577654813:web:ca07c3aab89a5bca7118f4',
    messagingSenderId: '359577654813',
    projectId: 'mission-board-b8dbc',
    authDomain: 'mission-board-b8dbc.firebaseapp.com',
    storageBucket: 'mission-board-b8dbc.firebasestorage.app',
    measurementId: 'G-1S7FED5QZH',
  );
}
